plugins {
    id 'com.android.application'
}

android {
    namespace 'app.onami.flashcards'
    compileSdk 30

    defaultConfig {
        applicationId 'app.onami.flashcards'
        minSdk 23
        targetSdk 30
        versionCode = Integer.parseInt(System.getenv('ONAMI_VERSION_CODE') ?: '1')
        versionName = System.getenv('ONAMI_VERSION_NAME') ?: '0.1.0'
    }
}
